/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as OrgsRouteImport } from './routes/orgs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppEntitiesNameRouteImport } from './routes/app.entities.$name'
import { Route as AppDashboardsSlugRouteImport } from './routes/app.dashboards.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsRoute = OrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesNameRoute = AppEntitiesNameRouteImport.update({
  id: '/entities/$name',
  path: '/entities/$name',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsSlugRoute = AppDashboardsSlugRouteImport.update({
  id: '/dashboards/$slug',
  path: '/dashboards/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/app/': typeof AppIndexRoute
  '/app/dashboards/$slug': typeof AppDashboardsSlugRoute
  '/app/entities/$name': typeof AppEntitiesNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/app': typeof AppIndexRoute
  '/app/dashboards/$slug': typeof AppDashboardsSlugRoute
  '/app/entities/$name': typeof AppEntitiesNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/app/': typeof AppIndexRoute
  '/app/dashboards/$slug': typeof AppDashboardsSlugRoute
  '/app/entities/$name': typeof AppEntitiesNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot'
    | '/login'
    | '/orgs'
    | '/reset'
    | '/signup'
    | '/app/'
    | '/app/dashboards/$slug'
    | '/app/entities/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/orgs'
    | '/reset'
    | '/signup'
    | '/app'
    | '/app/dashboards/$slug'
    | '/app/entities/$name'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot'
    | '/login'
    | '/orgs'
    | '/reset'
    | '/signup'
    | '/app/'
    | '/app/dashboards/$slug'
    | '/app/entities/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  OrgsRoute: typeof OrgsRoute
  ResetRoute: typeof ResetRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entities/$name': {
      id: '/app/entities/$name'
      path: '/entities/$name'
      fullPath: '/app/entities/$name'
      preLoaderRoute: typeof AppEntitiesNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboards/$slug': {
      id: '/app/dashboards/$slug'
      path: '/dashboards/$slug'
      fullPath: '/app/dashboards/$slug'
      preLoaderRoute: typeof AppDashboardsSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDashboardsSlugRoute: typeof AppDashboardsSlugRoute
  AppEntitiesNameRoute: typeof AppEntitiesNameRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDashboardsSlugRoute: AppDashboardsSlugRoute,
  AppEntitiesNameRoute: AppEntitiesNameRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  OrgsRoute: OrgsRoute,
  ResetRoute: ResetRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
