/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as OrgsRouteImport } from './routes/orgs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTimeRouteImport } from './routes/app.time'
import { Route as AppFlowsRouteImport } from './routes/app.flows'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppFlowsIndexRouteImport } from './routes/app.flows.index'
import { Route as AppSettingsPreferencesRouteImport } from './routes/app.settings.preferences'
import { Route as AppSettingsLlmRouteImport } from './routes/app.settings.llm'
import { Route as AppSettingsConnectorsRouteImport } from './routes/app.settings.connectors'
import { Route as AppFlowsNewRouteImport } from './routes/app.flows.new'
import { Route as AppFlowsIdRouteImport } from './routes/app.flows.$id'
import { Route as AppFlow_runsRunIdRouteImport } from './routes/app.flow_runs.$runId'
import { Route as AppEntitiesNameRouteImport } from './routes/app.entities.$name'
import { Route as AppDashboardsSlugRouteImport } from './routes/app.dashboards.$slug'
import { Route as AppFlowsIdIndexRouteImport } from './routes/app.flows.$id.index'
import { Route as AppFlowsIdRunsRunIdRouteImport } from './routes/app.flows.$id.runs.$runId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsRoute = OrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsRoute = AppFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsIndexRoute = AppFlowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFlowsRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLlmRoute = AppSettingsLlmRouteImport.update({
  id: '/settings/llm',
  path: '/settings/llm',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsConnectorsRoute = AppSettingsConnectorsRouteImport.update({
  id: '/settings/connectors',
  path: '/settings/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsNewRoute = AppFlowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppFlowsRoute,
} as any)
const AppFlowsIdRoute = AppFlowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFlowsRoute,
} as any)
const AppFlow_runsRunIdRoute = AppFlow_runsRunIdRouteImport.update({
  id: '/flow_runs/$runId',
  path: '/flow_runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesNameRoute = AppEntitiesNameRouteImport.update({
  id: '/entities/$name',
  path: '/entities/$name',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsSlugRoute = AppDashboardsSlugRouteImport.update({
  id: '/dashboards/$slug',
  path: '/dashboards/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsIdIndexRoute = AppFlowsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFlowsIdRoute,
} as any)
const AppFlowsIdRunsRunIdRoute = AppFlowsIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppFlowsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/flows': typeof AppFlowsRouteWithChildren
  '/app/time': typeof AppTimeRoute
  '/app/': typeof AppIndexRoute
  '/app/dashboards/$slug': typeof AppDashboardsSlugRoute
  '/app/entities/$name': typeof AppEntitiesNameRoute
  '/app/flow_runs/$runId': typeof AppFlow_runsRunIdRoute
  '/app/flows/$id': typeof AppFlowsIdRouteWithChildren
  '/app/flows/new': typeof AppFlowsNewRoute
  '/app/settings/connectors': typeof AppSettingsConnectorsRoute
  '/app/settings/llm': typeof AppSettingsLlmRoute
  '/app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/app/flows/': typeof AppFlowsIndexRoute
  '/app/flows/$id/': typeof AppFlowsIdIndexRoute
  '/app/flows/$id/runs/$runId': typeof AppFlowsIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/time': typeof AppTimeRoute
  '/app': typeof AppIndexRoute
  '/app/dashboards/$slug': typeof AppDashboardsSlugRoute
  '/app/entities/$name': typeof AppEntitiesNameRoute
  '/app/flow_runs/$runId': typeof AppFlow_runsRunIdRoute
  '/app/flows/new': typeof AppFlowsNewRoute
  '/app/settings/connectors': typeof AppSettingsConnectorsRoute
  '/app/settings/llm': typeof AppSettingsLlmRoute
  '/app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/app/flows': typeof AppFlowsIndexRoute
  '/app/flows/$id': typeof AppFlowsIdIndexRoute
  '/app/flows/$id/runs/$runId': typeof AppFlowsIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/flows': typeof AppFlowsRouteWithChildren
  '/app/time': typeof AppTimeRoute
  '/app/': typeof AppIndexRoute
  '/app/dashboards/$slug': typeof AppDashboardsSlugRoute
  '/app/entities/$name': typeof AppEntitiesNameRoute
  '/app/flow_runs/$runId': typeof AppFlow_runsRunIdRoute
  '/app/flows/$id': typeof AppFlowsIdRouteWithChildren
  '/app/flows/new': typeof AppFlowsNewRoute
  '/app/settings/connectors': typeof AppSettingsConnectorsRoute
  '/app/settings/llm': typeof AppSettingsLlmRoute
  '/app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/app/flows/': typeof AppFlowsIndexRoute
  '/app/flows/$id/': typeof AppFlowsIdIndexRoute
  '/app/flows/$id/runs/$runId': typeof AppFlowsIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot'
    | '/login'
    | '/orgs'
    | '/reset'
    | '/signup'
    | '/app/approvals'
    | '/app/flows'
    | '/app/time'
    | '/app/'
    | '/app/dashboards/$slug'
    | '/app/entities/$name'
    | '/app/flow_runs/$runId'
    | '/app/flows/$id'
    | '/app/flows/new'
    | '/app/settings/connectors'
    | '/app/settings/llm'
    | '/app/settings/preferences'
    | '/app/flows/'
    | '/app/flows/$id/'
    | '/app/flows/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/orgs'
    | '/reset'
    | '/signup'
    | '/app/approvals'
    | '/app/time'
    | '/app'
    | '/app/dashboards/$slug'
    | '/app/entities/$name'
    | '/app/flow_runs/$runId'
    | '/app/flows/new'
    | '/app/settings/connectors'
    | '/app/settings/llm'
    | '/app/settings/preferences'
    | '/app/flows'
    | '/app/flows/$id'
    | '/app/flows/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot'
    | '/login'
    | '/orgs'
    | '/reset'
    | '/signup'
    | '/app/approvals'
    | '/app/flows'
    | '/app/time'
    | '/app/'
    | '/app/dashboards/$slug'
    | '/app/entities/$name'
    | '/app/flow_runs/$runId'
    | '/app/flows/$id'
    | '/app/flows/new'
    | '/app/settings/connectors'
    | '/app/settings/llm'
    | '/app/settings/preferences'
    | '/app/flows/'
    | '/app/flows/$id/'
    | '/app/flows/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  OrgsRoute: typeof OrgsRoute
  ResetRoute: typeof ResetRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/time': {
      id: '/app/time'
      path: '/time'
      fullPath: '/app/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flows': {
      id: '/app/flows'
      path: '/flows'
      fullPath: '/app/flows'
      preLoaderRoute: typeof AppFlowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flows/': {
      id: '/app/flows/'
      path: '/'
      fullPath: '/app/flows/'
      preLoaderRoute: typeof AppFlowsIndexRouteImport
      parentRoute: typeof AppFlowsRoute
    }
    '/app/settings/preferences': {
      id: '/app/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/app/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/llm': {
      id: '/app/settings/llm'
      path: '/settings/llm'
      fullPath: '/app/settings/llm'
      preLoaderRoute: typeof AppSettingsLlmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/connectors': {
      id: '/app/settings/connectors'
      path: '/settings/connectors'
      fullPath: '/app/settings/connectors'
      preLoaderRoute: typeof AppSettingsConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flows/new': {
      id: '/app/flows/new'
      path: '/new'
      fullPath: '/app/flows/new'
      preLoaderRoute: typeof AppFlowsNewRouteImport
      parentRoute: typeof AppFlowsRoute
    }
    '/app/flows/$id': {
      id: '/app/flows/$id'
      path: '/$id'
      fullPath: '/app/flows/$id'
      preLoaderRoute: typeof AppFlowsIdRouteImport
      parentRoute: typeof AppFlowsRoute
    }
    '/app/flow_runs/$runId': {
      id: '/app/flow_runs/$runId'
      path: '/flow_runs/$runId'
      fullPath: '/app/flow_runs/$runId'
      preLoaderRoute: typeof AppFlow_runsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entities/$name': {
      id: '/app/entities/$name'
      path: '/entities/$name'
      fullPath: '/app/entities/$name'
      preLoaderRoute: typeof AppEntitiesNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboards/$slug': {
      id: '/app/dashboards/$slug'
      path: '/dashboards/$slug'
      fullPath: '/app/dashboards/$slug'
      preLoaderRoute: typeof AppDashboardsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flows/$id/': {
      id: '/app/flows/$id/'
      path: '/'
      fullPath: '/app/flows/$id/'
      preLoaderRoute: typeof AppFlowsIdIndexRouteImport
      parentRoute: typeof AppFlowsIdRoute
    }
    '/app/flows/$id/runs/$runId': {
      id: '/app/flows/$id/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/app/flows/$id/runs/$runId'
      preLoaderRoute: typeof AppFlowsIdRunsRunIdRouteImport
      parentRoute: typeof AppFlowsIdRoute
    }
  }
}

interface AppFlowsIdRouteChildren {
  AppFlowsIdIndexRoute: typeof AppFlowsIdIndexRoute
  AppFlowsIdRunsRunIdRoute: typeof AppFlowsIdRunsRunIdRoute
}

const AppFlowsIdRouteChildren: AppFlowsIdRouteChildren = {
  AppFlowsIdIndexRoute: AppFlowsIdIndexRoute,
  AppFlowsIdRunsRunIdRoute: AppFlowsIdRunsRunIdRoute,
}

const AppFlowsIdRouteWithChildren = AppFlowsIdRoute._addFileChildren(
  AppFlowsIdRouteChildren,
)

interface AppFlowsRouteChildren {
  AppFlowsIdRoute: typeof AppFlowsIdRouteWithChildren
  AppFlowsNewRoute: typeof AppFlowsNewRoute
  AppFlowsIndexRoute: typeof AppFlowsIndexRoute
}

const AppFlowsRouteChildren: AppFlowsRouteChildren = {
  AppFlowsIdRoute: AppFlowsIdRouteWithChildren,
  AppFlowsNewRoute: AppFlowsNewRoute,
  AppFlowsIndexRoute: AppFlowsIndexRoute,
}

const AppFlowsRouteWithChildren = AppFlowsRoute._addFileChildren(
  AppFlowsRouteChildren,
)

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppFlowsRoute: typeof AppFlowsRouteWithChildren
  AppTimeRoute: typeof AppTimeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDashboardsSlugRoute: typeof AppDashboardsSlugRoute
  AppEntitiesNameRoute: typeof AppEntitiesNameRoute
  AppFlow_runsRunIdRoute: typeof AppFlow_runsRunIdRoute
  AppSettingsConnectorsRoute: typeof AppSettingsConnectorsRoute
  AppSettingsLlmRoute: typeof AppSettingsLlmRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppFlowsRoute: AppFlowsRouteWithChildren,
  AppTimeRoute: AppTimeRoute,
  AppIndexRoute: AppIndexRoute,
  AppDashboardsSlugRoute: AppDashboardsSlugRoute,
  AppEntitiesNameRoute: AppEntitiesNameRoute,
  AppFlow_runsRunIdRoute: AppFlow_runsRunIdRoute,
  AppSettingsConnectorsRoute: AppSettingsConnectorsRoute,
  AppSettingsLlmRoute: AppSettingsLlmRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  OrgsRoute: OrgsRoute,
  ResetRoute: ResetRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
